version: "3.8"
services:
  nathan-programs_dev:
    build:
      dockerfile: dockerfiles/Dev.Dockerfile
      args:
        - m=3g
    volumes:
      - ~/Website/nathan-programs:/nathan-programs
    ports:
      - "8080:8080"

  nathan-programs_prod:
    image: nathansuss/nathan-programs:production
    ports:
      - "80:80"