services:
  setup:
    user: "1000:1000" # user id:group id (allows us to write whether in docker or on local machine)
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    build:
      dockerfile: dockerfiles/Setup.Dockerfile
      args: 
        - m=3g
    volumes:
      - ${PWD}:/Yay   # want to create new apps in this directory, so PWD
  dev:
    user: "1000:1000" # user id:group id
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    build:
      dockerfile: dockerfiles/Dev.Dockerfile
      args: 
        - m=3g
    volumes:
      - ${PWD}/${VUE_APP_NAME}:/Yay
    ports:
      - "8080:8080"

  prod:
    image: ${DOCKER_USERNAME}/${VUE_APP_NAME}:production
    ports:
      - "80:80"